### PR TITLE
Fix map decode error issue #259

### LINKED ISSUE #259: Map里面的decimal类型无法解析
**What happened**:
Java测，如果Map里面塞入decimal类型，解析会失败。

**What you expected to happen**:
Java测，如果Map里面塞入decimal类型，可以正常解析。

**How to reproduce it (as minimally and precisely as possible)**:

如下图所示，如果在Map中塞入一个decimal类型，dubbo-go这边将会解析失败。

image

image

### PR DESCRIPTION
**Pull request by wongoo**
**What this PR does**:
Fix map decode error issue 

**Which issue(s) this PR fixes**:

Fixes #259

**Special notes for your reviewer**:
the map type should be added into type map, not the class def map. see http://hessian.caucho.com/doc/hessian-serialization.html##type-map

**Does this PR introduce a user-facing change?**:
```release-note
- Fix map decode error issue #259 
```

### CODE REVIEW

File: object.go [hunk 1]
```diff
@@ -22,9 +22,7 @@ import (
 	"reflect"
 	"strings"
 	"sync"
-)
 
-import (
 	perrors "github.com/pkg/errors"
```
Comment (zouyx) [inline object.go:26]: not split?

**Review by zouyx — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

**Review by wenxuwan — APPROVED** [review]
